- .github/workflows/azure-dev-build-only.yml
- test/OpenChat.PlaygroundApp.Tests/Components/Pages/Chat/ChatHeaderUITests.cs
- test/OpenChat.PlaygroundApp.Tests/OpenChat.PlaygroundApp.Tests.csproj
Resolves #15
* Playwright UI 테스트를 위한 dependency 추가
* NUnit3TestAdapter
* Microsoft.Playwright.NUnit
* ChatHeaderUITest.cs 추가
> Add Playwright UI test sample for ChatHeader components

- src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
* Close #320 
* Refactor the `DisplayHelp()` method to avoid future conflict while collaborating.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[x] No
[ ] N/A
```
> Refactor `DisplayHelp()`

- src/OpenChat.PlaygroundApp/appsettings.json
- Add Upstage section with endpoint, token, and model settings
- Configure solar-pro2 as default model
Related to #353
* Adds configuration section for Upstage Solar API
* Enables support for `solar-pro2` model  
* Follows existing configuration pattern used by `GitHubModels`
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[ ] No
[x] N/A
```
```
git clone https://github.com/gremh97/open-chat-playground.git
git checkout …
```
> feat: add Upstage Solar API configuration to appsettings.json

- src/OpenChat.PlaygroundApp/Configurations/HuggingFaceSettings.cs
- #285  
Implement the Hugging Face `appsettings.json` using `LanguageModelSettings` as the base.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[ ] No
[x] N/A
```
> feat: add Hugging Face settings configuration

- src/OpenChat.PlaygroundApp/Options/HuggingFaceArgumentOptions.cs
#335  
Implement the options from HuggingFace's appsettings.json as a model.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[ ] No
[x] N/A
```
> feat: add Hugging Face argument options class

- src/OpenChat.PlaygroundApp/appsettings.json
This pull request adds configuration support for a new Azure AI Foundry integration in the application settings. The most important change is the addition of a new section for Azure AI Foundry credentials and model configuration.
Closes #323
**Configuration changes:**
* Added an `AzureAIFoundry` section to `appsettings.json` with `Endpoint`, `ApiKey`, and `Model` fields to enable integration with Azure AI Foundry services.## Purpose
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
The top-level readme for this repo contains a link to each sample in the repo. If you're adding a new sample did you update the …
> feat: add OpenAI settings to appsettings.json

- licenses/azure.ai.openai.md
- src/OpenChat.PlaygroundApp/OpenChat.PlaygroundApp.csproj
* Added Azure AI OpenAI NuGet Package to enable Azure AI Foundry
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] New feature
```
```
[ ] Yes
[ ] No
[X] N/A
```
> Add Azure.AI.OpenAI NuGet package for Azure AI Foundry support

- src/OpenChat.PlaygroundApp/OpenChat.PlaygroundApp.csproj
* Add a NuGet package for Hugging Face that supports Microsoft.Extensions.AI to .csproj.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Other... Please describe: Add a NuGet package
```
```
[ ] Yes
[ ] No
[x] N/A
```
```
git clone https://github.com/ummjevel/open-chat-playground.git
git checkout feature/337-addnuget-hf
```
```
dotnet restore
dotnet build src/OpenChat.PlaygroundApp/OpenChat.PlaygroundApp.csproj
dotnet list …
```
> feat: Add NuGet package: Hugging Face #337

- src/OpenChat.PlaygroundApp/Configurations/OpenAISettings.cs
* #217 : a new configuration class for managing OpenAI settings within the application.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[ ] No
[x] N/A
```
* Added a new `OpenAISettings` class that inherits from `LanguageModelSettings`, with properties for `ApiKey` and `Model` to store OpenAI-specific configuration.
* Updated the `AppSettings` class to include an `OpenAI` property, allowing the application to access and manage …
> feat: Model Class Implementation - OpenAI GPT

- src/OpenChat.PlaygroundApp/appsettings.json
Closes #326
* Add API connection details for Google Vertex AI to appsettings.json
* Assume that use [Mscc.GenerativeAI](https://github.com/mscraftsman/generative-ai)
* Why Mscc.GenerativeAI?
* [Google.Cloud.AIPlatform.V1](https://cloud.google.com/dotnet/docs/reference/Google.Cloud.AIPlatform.V1/latest) does not support Microsoft.Extensions.AI
* [Google_GenerativeAI](https://github.com/gunpal5/Google_GenerativeAI) supports Microsoft.Extensions.AI, but...
* Only the Generative Language API can be used with Microsoft.Extensions.AI
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
The top-level readme for this …
> feat: add Google Vertex AI settings params to appsettings.json

- src/OpenChat.PlaygroundApp/Options/OllamaArgumentOptions.cs
Closes #338 
* Command-Line Argument Options Modelling: Ollama  #338 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[ ] No
[x] N/A
```
```
git clone https://github.com/donghyeon639/open-chat-playground.git
git checkout feat/338-Command-Line-Argument-Options-Modelling-Ollama
```
* Check if the command line arguments include baseurl and model name.
* By ArgumentOption.cs, the class name …
> feat: Add OllamaArgumentOptions for command-line argument modelling

- src/OpenChat.PlaygroundApp/appsettings.json
Closes #333
* Add API connection details for Foundry Local to appsettings.json
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[ ] No
[x] N/A
```
```
git clone https://github.com/sikutisa/open-chat-playground.git
git switch feature/333-appsettings-modelling-foundry-local
```
```
cat src/OpenChat.PlaygroundApp/appsettings.json
dotnet build src/OpenChat.PlaygroundApp
dotnet run --project …
```
> feat: add API connection details of Foundry Local to appsettings.json

- src/OpenChat.PlaygroundApp/Configurations/AzureAIFoundrySettings.cs
- https://github.com/aliencube/open-chat-playground/issues/186 : a new configuration class for managing Azure AI Foundry settings within the application.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[x] No
[ ] N/A
```
- Added a new AzureAIFoundrySettings class that inherits from LanguageModelSettings.
> feat: Add new AzureAIFoundrySettings

- README.md
- src/OpenChat.PlaygroundApp/appsettings.json
* This pull request is for setting up Amazon Bedrock in the application.
* **Region**: When you specify a region, the AWS SDK automatically uses the default endpoint for that region. Therefore, I specified the *Region* instead of the *Endpoint*. ([AWS service endpoints](https://docs.aws.amazon.com/general/latest/gr/rande.html?utm_source=chatgpt.com))
* **Model**: I set it to the latest Claude model supported in the ap-northeast-2 region where Korea is located. ([Supported foundation models in Amazon Bedrock](https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html))
Closes #318 
<br>
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Documentation content …
```
> feat: add Amazon Bedrock configuration to appsettings.json

- src/OpenChat.PlaygroundApp/Options/AzureAIFoundryArgumentOptions.cs
* #322
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[x] No
[ ] N/A
```
> feat: add Command-Line Argument Options Modeling for Azure AI Foundry

- src/OpenChat.PlaygroundApp/Options/GoogleVertexAIArgumentOptions.cs
- test/OpenChat.PlaygroundApp.Tests/Abstractions/ArgumentOptionsTests.cs
Closes #325
* Command-Line argument options modelling for Google Vertex AI
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[ ] No
[x] N/A
```
```
git clone https://github.com/sikutisa/open-chat-playground.git
git checkout [branch-name]
```
* Verify that the following are valid
* Check if the command line arguments include `ApiKey` and `Model`
* By ArgumentOption.cs, the class name must be `GoogleVertexAIArgumentOptions`
* …
> feat: add GoogleVertexAIArgumentOptions.cs

- src/OpenChat.PlaygroundApp/Configurations/FoundryLocalSettings.cs
* Model Class Implementation: Foundry Local 
* closes #211
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[ ] No
[x] N/A
```
* It represents the Foundry Local json model submitted through #388 PR
```
"FoundryLocal": {
"Alias": "phi-4-mini"
},
```
> Model Class Implementation: Foundry Local #211

- src/OpenChat.PlaygroundApp/appsettings.json
This pull request adds configuration support for a new LG EXAONE integration in the application settings. The most important change is the addition of a new section for LG EXAONE credentials and model configuration through OllamaSharp.
Closes #345 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[x] No
[ ] N/A
```
Get the code
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
```
Test the code
```
dotnet build
dotnet run --project …
```
> LG exaone app settings

- src/OpenChat.PlaygroundApp/Configurations/AmazonBedrockSettings.cs
* This PR adds a new configuration class for Amazon Bedrock settings.
* It represents the appsettings model, and I’ve followed the conventions used in other Settings classes.
Closes #225
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[x] No
[ ] N/A
```
> feat: add Amazon Bedrock settings configuration class

- test/OpenChat.PlaygroundApp.Tests/Abstractions/ArgumentOptionsTests.cs
- test/OpenChat.PlaygroundApp.Tests/Abstractions/LanguageModelConnectorTests.cs
- test/OpenChat.PlaygroundApp.Tests/Abstractions/LanguageModelSettings.cs
Closes #423
* Add test codes to check that...
* XXXArgumentOptions classes inherit ArgumentOptions.
* XXXSettings classes inherit LanguageModelSettings.
* XXXConnector classes inherit LanguageModelConnector.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Other... Please describe: Add more tests
```
```
[ ] Yes
[x] No
[ ] N/A
```
```
dotnet test --filter "Category=UnitTest"
```
* All tests must be passed
> enhance: add inheritance tests

- src/OpenChat.PlaygroundApp/Abstractions/ArgumentOptions.cs
- src/OpenChat.PlaygroundApp/Options/AzureAIFoundryArgumentOptions.cs
- test/OpenChat.PlaygroundApp.Tests/Options/AzureAIFoundryArgumentOptionsTests.cs
* Command-Line Argument Parsing: Azure AI Foundry: https://github.com/aliencube/open-chat-playground/issues/187
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[x] No
[ ] N/A
```
- run test
```csharp
dotnet test --filter Category=UnitTest
```
> feat: add parsing Command-Line Argument for Azure AI Foundry

- src/OpenChat.PlaygroundApp/Configurations/DockerModelRunnerSettings.cs
- test/OpenChat.PlaygroundApp.Tests/Abstractions/LanguageModelSettings.cs
Closes #276
* Add model class for Docer Model Runner.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[x] No
[ ] N/A
```
```
dotnet test --filter "Category=UnitTest"
```
* Check the model calss fields include `BaseUrl` and `Model`
* Must pass all unit tests
> feat: add DocerModelRunnerSettings

- test/OpenChat.PlaygroundApp.Tests/Options/AnthropicArgumentOptionsTests.cs
- close #260 
Ensure Anthropic Claude configuration values are loaded from environment variables and that command-line arguments take precedence when provided. Add or adjust unit tests to verify env loading and CLI override behavior, reducing related test flakiness.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Other... Please describe: (test)enhance Anthropic Claude argument options test
```
```
[ ] Yes
[ ] No
[x] N/A
```
* run test
```
dotnet test --filter Category=UnitTest
```
Verify that the …
> Environment Variables Testing: Anthropic Claude

- docs/github-models.md
- docs/hugging-face.md
- docs/openai.md
* Each model doc needs to provide its model links in the beginning of the page. This PR adds those links to each doc.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Documentation content changes
```
```
[ ] Yes
[x] No
[ ] N/A
```
> Update docs to provide models page in the beginning

- README.md
- src/OpenChat.PlaygroundApp/OpenChat.PlaygroundApp.csproj
- src/OpenChat.PlaygroundApp/Program.cs
* Close #483 
* It defines the API endpoint with placeholder data.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Documentation content changes
```
```
[x] Yes
[ ] No
[ ] N/A
```
* Run the app by the command with all default options (GitHub Models):
```bash
dotnet watch run --project ./src/OpenChat.Playground
```
* Navigate to `http://localhost:5280/openapi.json` and verify the OpenAPI doc is properly rendered.
* Send an API request to the endpoint, `http://localhost:5280/api/chat/responses` …
> Define endpoint

- src/OpenChat.PlaygroundApp/Services/ChatService.cs
- test/OpenChat.PlaygroundApp.Tests/Services/ChatServiceTests.cs
* Close #482 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
```
```
[ ] Yes
[x] No
[ ] N/A
```
```
dotnet test . --filter "Category=UnitTest"
```
* Verify passing all unit tests.
> Add `ChatService`

- azure.yaml
- docs/github-models.md
- docs/hugging-face.md
- docs/openai.md
- infra/main.bicep
- infra/main.parameters.json
- infra/resources.bicep
- src/OpenChat.PlaygroundApp/Connectors/GitHubModelsConnector.cs
- src/OpenChat.PlaygroundApp/Connectors/HuggingFaceConnector.cs
- src/OpenChat.PlaygroundApp/Connectors/OpenAIConnector.cs
- test/OpenChat.PlaygroundApp.Tests/Abstractions/LanguageModelConnectorTests.cs
- test/OpenChat.PlaygroundApp.Tests/Connectors/GitHubModelsConnectorTests.cs
- test/OpenChat.PlaygroundApp.Tests/Connectors/HuggingFaceConnectorTests.cs
- test/OpenChat.PlaygroundApp.Tests/Connectors/OpenAIConnectorTests.cs
* Close #491 
* Connectors like Hugging Face, Ollama and LG use Ollama as a local LLM server. When the OCP app is deployed to the cloud, the Ollama server has to be deployed as well. This PR is to provision/deploy the Ollama server for those three connectors.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Documentation content changes
```
```
[ ] Yes
[x] No
[ ] N/A
```
```
dotnet test . --filter "Category=UnitTest"
```
* Deploy to Azure by following `docs/hugging-face.md` and …
> Update bicep files to serve Ollama server
